quarkus.s3.aws.region=eu-north-1
quarkus.s3.endpoint-override=https://s3.eu-north-1.amazonaws.com

quarkus.s3.aws.credentials.type=default
quarkus.s3.aws.credentials.profile-provider.profile-name=default
quarkus.s3.profile-name=default

quarkus.http.port=8085

quarkus.s3.aws.credentials.static-provider.access-key-id=${ACCESS_KEY_ID}
quarkus.s3.aws.credentials.static-provider.secret-access-key=${SECRET_ACCESS_KEY}

quarkus.rest-client.user-service.url=http://localhost:8083


mp.jwt.token.header=Cookie
mp.jwt.token.cookie=JwtToken
